/* This file is generated by Ziggy. */
declare module 'ziggy-js' {
  interface RouteList {
    "login": [],
    "login.store": [],
    "logout": [],
    "password.confirm": [],
    "password.confirmation": [],
    "password.confirm.store": [],
    "two-factor.login": [],
    "two-factor.login.store": [],
    "two-factor.enable": [],
    "two-factor.confirm": [],
    "two-factor.disable": [],
    "two-factor.qr-code": [],
    "two-factor.secret-key": [],
    "two-factor.recovery-codes": [],
    "two-factor.regenerate-recovery-codes": [],
    "home": [],
    "dashboard": [],
    "transactions.index": [],
    "transactions.create": [],
    "transactions.show": [
        {
            "name": "transaction",
            "required": true,
            "binding": "id"
        }
    ],
    "transactions.store": [],
    "categories.index": [],
    "categories.create": [],
    "categories.store": [],
    "categories.show": [
        {
            "name": "category",
            "required": true
        }
    ],
    "categories.edit": [
        {
            "name": "category",
            "required": true
        }
    ],
    "categories.update": [
        {
            "name": "category",
            "required": true,
            "binding": "id"
        }
    ],
    "categories.destroy": [
        {
            "name": "category",
            "required": true,
            "binding": "id"
        }
    ],
    "accounts.index": [],
    "accounts.create": [],
    "accounts.store": [],
    "accounts.edit": [
        {
            "name": "account",
            "required": true
        }
    ],
    "accounts.update": [
        {
            "name": "account",
            "required": true,
            "binding": "id"
        }
    ],
    "accounts.destroy": [
        {
            "name": "account",
            "required": true,
            "binding": "id"
        }
    ],
    "budgets.index": [],
    "budgets.store": [],
    "reports.index": [],
    "financial-goals.add-savings": [
        {
            "name": "financialGoal",
            "required": true,
            "binding": "id"
        }
    ],
    "financial-goals.index": [],
    "financial-goals.create": [],
    "financial-goals.store": [],
    "financial-goals.show": [
        {
            "name": "financial_goal",
            "required": true
        }
    ],
    "financial-goals.edit": [
        {
            "name": "financial_goal",
            "required": true
        }
    ],
    "financial-goals.update": [
        {
            "name": "financial_goal",
            "required": true
        }
    ],
    "financial-goals.destroy": [
        {
            "name": "financial_goal",
            "required": true
        }
    ],
    "debts.record-payment": [
        {
            "name": "debt",
            "required": true,
            "binding": "id"
        }
    ],
    "debts.index": [],
    "debts.create": [],
    "debts.store": [],
    "debts.show": [
        {
            "name": "debt",
            "required": true
        }
    ],
    "debts.edit": [
        {
            "name": "debt",
            "required": true
        }
    ],
    "debts.update": [
        {
            "name": "debt",
            "required": true
        }
    ],
    "debts.destroy": [
        {
            "name": "debt",
            "required": true
        }
    ],
    "parties.index": [],
    "parties.create": [],
    "parties.store": [],
    "parties.show": [
        {
            "name": "party",
            "required": true
        }
    ],
    "parties.edit": [
        {
            "name": "party",
            "required": true
        }
    ],
    "parties.update": [
        {
            "name": "party",
            "required": true
        }
    ],
    "parties.destroy": [
        {
            "name": "party",
            "required": true
        }
    ],
    "recurring-transactions.index": [],
    "recurring-transactions.create": [],
    "recurring-transactions.store": [],
    "recurring-transactions.show": [
        {
            "name": "recurring_transaction",
            "required": true
        }
    ],
    "recurring-transactions.edit": [
        {
            "name": "recurring_transaction",
            "required": true
        }
    ],
    "recurring-transactions.update": [
        {
            "name": "recurring_transaction",
            "required": true
        }
    ],
    "recurring-transactions.destroy": [
        {
            "name": "recurring_transaction",
            "required": true
        }
    ],
    "profile.edit": [],
    "profile.update": [],
    "profile.destroy": [],
    "password.edit": [],
    "password.update": [],
    "appearance": [],
    "two-factor.show": [],
    "register": [],
    "register.store": [],
    "password.request": [],
    "password.email": [],
    "password.reset": [
        {
            "name": "token",
            "required": true
        }
    ],
    "password.store": [],
    "verification.notice": [],
    "verification.verify": [
        {
            "name": "id",
            "required": true
        },
        {
            "name": "hash",
            "required": true
        }
    ],
    "verification.send": [],
    "storage.local": [
        {
            "name": "path",
            "required": true
        }
    ]
}
}
export {};
